"""empty message

Revision ID: 9da1e1134058
Revises: 1a94cf7515a5
Create Date: 2022-02-19 15:29:27.545384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9da1e1134058'
down_revision = '1a94cf7515a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'due_by',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('tasks_due_by_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_due_by_key', 'tasks', ['due_by'])
    op.alter_column('tasks', 'due_by',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
